name: Deploy to self-hosted runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: sudo docker compose -f "docker-compose.yml" up -d --build

      - name: Cleanup Docker
        run: |
          sudo docker system prune -af
          sudo docker volume prune -f
          sudo docker network prune -f
